version: '3.8'

services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  frontend-service:
    build:
      context: ./frontend-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  journal-service:
    build:
      context: ./journal-service
      dockerfile: Dockerfile
    environment:
      DB_URL: mongodb://rootuser:rootpass@mongodb:27017/SmartTraveller?authSource=admin
    ports:
      - "8082:8082"
    depends_on:
      - mongodb

  schedule-service:
    build:
      context: ./schedule-service
      dockerfile: Dockerfile
    environment:
      DB_URL: mongodb://rootuser:rootpass@mongodb:27017/SmartTraveller?authSource=admin
    ports:
      - "8083:8083"
    depends_on:
      - mongodb

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    environment:
      DB_URL: mongodb://rootuser:rootpass@mongodb:27017/SmartTraveller?authSource=admin
    ports:
      - "8081:8081"
    depends_on:
      - mongodb

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend-service
      - user-service
      - journal-service
      - schedule-service

volumes:
  mongo-data:

